name: Update gist with WakaTime stats

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 00:00 运行
    #- cron: "*/10 * * * *"  # 调试用，正式使用改为 "0 0 * * *"

jobs:
  build:
    name: Update-gist
    runs-on: ubuntu-latest
    env:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: b03a8abcd73cb837b741fe4fe1ad5997
      GIST_BARSTYLE: SOLIDLT
      GIST_BARLENGTH: -1
      GIST_TIMESTYLE: SHORT

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      
      - name: Install dependencies
        run: go mod download

      #- name: Check out code into the Go module directory
        #uses: actions/checkout@v2
      #- name: Debug env variables
        #run: |
          #echo "WAKATIME_API_KEY: $WAKATIME_API_KEY"
          #echo "GH_TOKEN: $GH_TOKEN"
          #echo "GIST_ID: $GIST_ID"

      - name: Update-gist
        run: go run ./cmd/box/main.go 
